// Generates js/data/coast.js: simplified real coastlines (Natural Earth 1:50m land)
// used to clip the map so countries keep their true shapes.
// Run with: npm run build-coast
'use strict';
const fs = require('fs');
const path = require('path');
const topo = require('topojson-client');
const atlas = require('world-atlas/land-50m.json');

const Q = 40;            // quantisation: 1/40 degree
const TOL = 0.035;       // Douglas-Peucker tolerance in degrees
const MIN_AREA = 0.02;   // drop specks smaller than this (square degrees)
const LAT_MIN = -58, LAT_MAX = 75.6;

function simplify(pts, tol) {
  if (pts.length < 5) return pts;
  const keep = new Uint8Array(pts.length); keep[0] = keep[pts.length - 1] = 1;
  const stack = [[0, pts.length - 1]];
  while (stack.length) {
    const [a, b] = stack.pop();
    let best = -1, bd = 0;
    const [x1, y1] = pts[a], [x2, y2] = pts[b], dx = x2 - x1, dy = y2 - y1, len = Math.hypot(dx, dy);
    for (let i = a + 1; i < b; i++) {
      const d = len < 1e-9 ? Math.hypot(pts[i][0] - x1, pts[i][1] - y1) : Math.abs(dy * pts[i][0] - dx * pts[i][1] + x2 * y1 - y2 * x1) / len;
      if (d > bd) { bd = d; best = i; }
    }
    if (bd > tol && best > 0) { keep[best] = 1; stack.push([a, best], [best, b]); }
  }
  return pts.filter((_, i) => keep[i]);
}
const area = r => { let s = 0; for (let i = 0, j = r.length - 1; i < r.length; j = i++) s += (r[j][0] + r[i][0]) * (r[j][1] - r[i][1]); return Math.abs(s / 2); };

const land = topo.feature(atlas, atlas.objects.land);
const rings = [];
for (const f of land.features || [land]) {
  const g = f.geometry;
  const polys = g.type === 'MultiPolygon' ? g.coordinates : [g.coordinates];
  for (const poly of polys) for (let ring of poly) {
    if (area(ring) < MIN_AREA) continue;
    const lats = ring.map(p => p[1]);
    if (Math.max(...lats) < LAT_MIN || Math.min(...lats) > LAT_MAX) continue;
    // rings that straddle the 180th meridian are unwrapped into one continuous shape
    // (each jump across it shifts the rest of the ring by 360 degrees, so the shape stays
    // continuous; the renderer draws the world three times side by side to cover the wrap)
    let shift = 0;
    ring = ring.map(([lo, la], i) => {
      if (i) { const prev = ring[i - 1][0]; if (lo - prev > 180) shift -= 360; else if (prev - lo > 180) shift += 360; }
      return [lo + shift, la];
    });
    // keep the shape's start inside the map (a ring that began east of the seam would
    // otherwise land a whole world to the left)
    const minLon = Math.min(...ring.map(p => p[0]));
    if (minLon < -180) ring = ring.map(([lo, la]) => [lo + 360, la]);
    const s = simplify(ring, TOL);
    if (s.length < 4) continue;
    let px = 0, py = 0;
    const out = [];
    for (const [lon, lat] of s) {
      const x = Math.round(lon * Q), y = Math.round(Math.max(LAT_MIN, Math.min(LAT_MAX, lat)) * Q);
      if (out.length && x === px && y === py) continue;
      out.push(x - px, y - py); px = x; py = y;
    }
    rings.push(out.map(v => v.toString(36)).join(','));
  }
}
const js = `// AUTO-GENERATED by tools/build-coast.js from Natural Earth 1:50m land (world-atlas). Do not edit.\nwindow.IM = window.IM || {};\nwindow.IM.COAST = { q: ${Q}, rings: ${JSON.stringify(rings)} };\n`;
fs.writeFileSync(path.join(__dirname, '..', 'js', 'data', 'coast.js'), js);
const pts = rings.reduce((a, r) => a + r.split(',').length / 2, 0);
console.log(`${rings.length} rings, ${pts} points, ${(js.length / 1024).toFixed(0)} KB`);
